//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tc.Inventio.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pages
    {
        public int Id { get; set; }
        public string GUID { get; set; }
        public string Path { get; set; }
        public string Title { get; set; }
        public int LayoutId { get; set; }
        public int State { get; set; }
        public string PubVersion { get; set; }
        public string Metadata { get; set; }
        public string MetadataVersion { get; set; }
        public Nullable<int> Action { get; set; }
        public Nullable<int> IdUser { get; set; }
    
        public virtual Layouts Layouts { get; set; }
    }
}
